// <auto-generated />
using System;
using BabsScoreDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BabsScoreDatabase.Migrations
{
    [DbContext(typeof(BABSScoresDbContext))]
    [Migration("20221116161446_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BabsScoreDatabase.Models.Database.Chorus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Chorus");
                });

            modelBuilder.Entity("BabsScoreDatabase.Models.Database.Contest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContestType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("YearId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("YearId");

                    b.ToTable("Contest");
                });

            modelBuilder.Entity("BabsScoreDatabase.Models.Database.Quartet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Quartet");
                });

            modelBuilder.Entity("BabsScoreDatabase.Models.Database.ScoreSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChorusId")
                        .HasColumnType("integer");

                    b.Property<int>("Mus")
                        .HasColumnType("integer");

                    b.Property<int>("Perf")
                        .HasColumnType("integer");

                    b.Property<int?>("QuartetId")
                        .HasColumnType("integer");

                    b.Property<int>("Sing")
                        .HasColumnType("integer");

                    b.Property<int?>("SongId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChorusId");

                    b.HasIndex("QuartetId");

                    b.HasIndex("SongId");

                    b.ToTable("ScoreSet");
                });

            modelBuilder.Entity("BabsScoreDatabase.Models.Database.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Song");
                });

            modelBuilder.Entity("BabsScoreDatabase.Models.Database.Year", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContestYear")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Year");
                });

            modelBuilder.Entity("BabsScoreDatabase.Models.Database.Contest", b =>
                {
                    b.HasOne("BabsScoreDatabase.Models.Database.Year", "Year")
                        .WithMany()
                        .HasForeignKey("YearId");

                    b.Navigation("Year");
                });

            modelBuilder.Entity("BabsScoreDatabase.Models.Database.ScoreSet", b =>
                {
                    b.HasOne("BabsScoreDatabase.Models.Database.Chorus", "Chorus")
                        .WithMany()
                        .HasForeignKey("ChorusId");

                    b.HasOne("BabsScoreDatabase.Models.Database.Quartet", "Quartet")
                        .WithMany()
                        .HasForeignKey("QuartetId");

                    b.HasOne("BabsScoreDatabase.Models.Database.Song", "Song")
                        .WithMany()
                        .HasForeignKey("SongId");

                    b.Navigation("Chorus");

                    b.Navigation("Quartet");

                    b.Navigation("Song");
                });
#pragma warning restore 612, 618
        }
    }
}
